#!/bin/bash
set -euo pipefail
#
# This script is intended to be run in the root of your sandbox, in the same location as your Makefile.
# remake will walk through the targets in the Makefile and generate callgrind formatted profile data
# gprof2dot will parse the profiling data and create a dot language script, and dot will generate a PNG
#

echo "Profiling Makefile"
touch /tmp/before
ls callgrind.out.* > /tmp/before || true
for target in $(remake --targets --no-builtin-rules | sed -e 's/^[[:space:]]*//' -e '/^\./d' | awk '{print $1}' | grep -v '%'); do
    remake --always-make --dry-run --profile ${target}
done
ls callgrind.out.* > /tmp/after
profile_files=$(comm -1 -3 /tmp/before /tmp/after | xargs)

echo "Creating digraphs"
dotfile=/tmp/makeviz.dot
echo "digraph {" > "${dotfile}"
for pfile in ${profile_files[@]}; do
    python3 /gprof2dot.py --format=callgrind "${pfile}" | sed -e 's/digraph/subgraph/' >> "${dotfile}"
    rm --one-file-system "${pfile}"
done
echo "}" >> "${dotfile}"

echo "Generating visualization"
dot -Tpng -o makeviz.png "${dotfile}"

